# site settings
title: bobb3666 devvin
subtitle: hacking through the hacking
email: 
description: A personal github page for bobb3666
baseurl: 
url: # the base hostname & protocol for your site
author:
street_address: 1234 Not Telling street_address
city: Melbourne
state: VIC
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/bobb666
gitlab_url: 
googleplus_url:
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
